---
title: "Beers"
author: "Neil Ritter"
date: "7/17/2017"
output: html_document
---

```{r}
library(rvest)
library(stringr)

```


## Methods for getting beer info from beer profile


```{r}
# Get beer name
get_beer_name <- function(beer_profile){
  
  beer_name <- html_nodes(beer_profile, "h1")
  beer_name <- str_extract(as.character(beer_name), "(?<=<h1>)(.*)(?=<span)")
  return(beer_name)
  
}
```

```{r}
# Get beer brewery
get_beer_brewery <- function(){
  
  brewery_name <- html_nodes(beer, ".titleBar span")
  # note - have to escape pipe symbol with two backslashes, e.g. \\|
  brewery_name <- str_extract(as.character(brewery_name), "(?<=\\| )(.*)(?=</span)")
  return(brewery_name)
}

```

```{r}
# Get beer global user rating
get_beer_user_rating <- function(beer_profile){
  
  beer_rating <- html_nodes(beer, ".ba-score")
  beer_rating <- str_extract(as.character(beer_rating), "(?<=>)(.*)(?=</span)")
  beer_rating <- as.numeric(beer_rating)
  
  return(beer_rating)

}

```


```{r}
# Get ABV

```





