---
title: "Beers"
author: "Neil Ritter"
date: "7/17/2017"
output: html_document
---

```{r}
library(rvest)
library(stringr)

```

## Methods for getting beer info from beer profile

```{r}
index <- 1
beer <- read_html(paste("/Users/Drazi/beerwizard/data/test/test_profiles/profile_", index, sep = ""))

```

```{r}
# Get beer name
get_beer_name <- function(beer_profile){
  
  beer_name <- html_nodes(beer_profile, "h1")
  beer_name <- str_extract(as.character(beer_name), "(?<=<h1>)(.*)(?=<span)")
  return(beer_name)
  
}
```

```{r}
# Get beer brewery
get_beer_brewery <- function(beer){
  
  brewery_name <- html_nodes(beer, ".titleBar span")
  # note - have to escape pipe symbol with two backslashes, e.g. \\|
  brewery_name <- str_extract(as.character(brewery_name), "(?<=\\| )(.*)(?=</span)")
  return(brewery_name)
}

```

```{r}
# Get beer global user rating
get_beer_user_rating <- function(beer_profile){
  
  beer_rating <- html_nodes(beer_profile, ".ba-score")
  beer_rating <- str_extract(as.character(beer_rating), "(?<=>)(.*)(?=</span)")
  beer_rating <- as.numeric(beer_rating)
  
  return(beer_rating)

}

```

```{r}
# Get beer style
get_beer_style <- function(beer_profile){
  
  beer_style <- html_nodes(beer_profile, "b+ a b")
  beer_style <- str_extract(as.character(beer_style), "(?<=<b>)(.*)(?=</b>)")
  
  return(beer_style)
  
}

```


```{r}
# Get ABV

```


```{r}
# Build beer information table

beerInfo <- data.frame(name = NA,
                       brewery = NA,
                       rating = 1:250) # makes data frame have 10 rows
                       
for(i in 1:250){
  beer <- read_html(
    paste("/Users/Drazi/beerwizard/data/top250/profiles/profile_", i, sep = ""))
  
  beerInfo$name[i] <- get_beer_name(beer)
  beerInfo$brewery[i] <- get_beer_brewery(beer)
  beerInfo$rating[i] <- get_beer_user_rating(beer)
  beerInfo$style[i] <- get_beer_style(beer)
  
}

# reorder beers to match term document matrix order
x <- 1:250
x <- as.character(x)
x <- order(x)
beerInfo <- beerInfo[x, ]

```


```{r}
# Save beerInfo

write.csv(beerInfo,
          file = "/Users/Drazi/beerwizard/data/profiles/beer_info.txt")

```




